# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import videocenter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animate', models.CharField(max_length=256)),
                ('animateEN', models.CharField(max_length=256)),
                ('Image', models.ImageField(upload_to=videocenter.models.AnimatePath)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animate', models.CharField(max_length=256)),
                ('animateEN', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('season', models.CharField(choices=[('1', 'Winter'), ('2', 'Spring'), ('3', 'Summer'), ('4', 'Autumn')], max_length=1)),
                ('is_end', models.BooleanField(default=True)),
                ('Image', models.ImageField(upload_to=videocenter.models.AnimatePath)),
                ('ImageBig', models.ImageField(upload_to=videocenter.models.AnimatePath)),
            ],
        ),
    ]
